# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'weather.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x07weather\"!\n\x11GetWeatherRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"\x8b\x01\n\x12GetWeatherResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0e\n\x06temp_c\x18\x02 \x01(\x01\x12\x14\n\x0chumidity_pct\x18\x03 \x01(\x05\x12\x12\n\nconditions\x18\x04 \x01(\t\x12\x15\n\rwind_speed_ms\x18\x05 \x01(\x01\x12\x16\n\x0e\x66\x65tched_at_iso\x18\x06 \x01(\t2^\n\x0eWeatherService\x12L\n\x11GetCurrentWeather\x12\x1a.weather.GetWeatherRequest\x1a\x1b.weather.GetWeatherResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETWEATHERREQUEST']._serialized_start=26
  _globals['_GETWEATHERREQUEST']._serialized_end=59
  _globals['_GETWEATHERRESPONSE']._serialized_start=62
  _globals['_GETWEATHERRESPONSE']._serialized_end=201
  _globals['_WEATHERSERVICE']._serialized_start=203
  _globals['_WEATHERSERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
